/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Brynn (https://sketchfab.com/Brynnnnn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mushroom-house-13774337157f4ac0a7e7fb3570de4bdc
Title: Mushroom House
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/mushroom_house.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.StingrayPBS2SG}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/mushroom_house.glb");
